### ISSUE TITLE
Constructor 'gets hit' twice

### ISSUE THREAD

**Issue by SenegeacStefan** [kevinohara80/sfdc-trigger-framework#10]
public class MyObjectTriggerHandler {
    public MyObjectTriggerHandler() {
        system.debug('==>constructor'); // in the log I see it two times
        this.setMaxLoopCount(1); //exception of course but I want to only run once! 
    }
...
}

trigger MyObjectTrigger on MyObject(all events) {
    new MyObjectTriggerHandler().run();
}

**Comment by renatoliveira** [comment]
`setMaxLoopCount` seems to be only to assert that the trigger runs only the amount of times specified, not to prevent it from running more times than specified.

To run a trigger only once you have to use the bypass API.

    TriggerHandler.bypass('MyTriggerHandler');
    update myitems; // update which will fire the same trigger again

This way when the trigger gets fired a second time, the handler will detect that it has to bypass this handler, and thus the recursivity will stop.

**Comment by SenegeacStefan** [comment]
Oh, I thought `setMaxLoopCount `did prevention. Anyway using `bypass` has no effect - constructor still gets hit twice.

**Comment by renatoliveira** [comment]
Well, yes. It will always get called because your handler is a class being called from a trigger, right? If you don't want your class' constructor to be called, then what you need to do is avoid the constructor being called on the trigger.

The point of the bypass is not to prevent the class from being called, but to prevent its methods from being run (the `after` and `before` overrides).

If you have some code that has to be run every time the class is run, consider creating a method for that, and calling it inside those overrides.

**Comment by SenegeacStefan** [comment]
That should've been obvious from the start. Thank you for clarification!
