### ISSUE TITLE
Handling iteration

### ISSUE THREAD

**Issue by pranayjswl007** [kevinohara80/sfdc-trigger-framework#14]
Inside every handler, every developer creates a new service method that iterates over the list of records and if the record matches the condition then execute the further logic. Now as project goes complex we end up adding more service method that reiterates over same set of records and executes logic again.

The problem here is , we end up iterating again and again, which eventually adds up to CPU timeout.

For eg: If a DML is performed for 200 records, and we have 8 service methods present, thus we end up iterating 200*8=1600 times while ideally we should only be iterating it 200times.

I have an idea that the TriggerHandler class should declare 6 new method prototypes.
beforeInsertIterator();
afterInsertIterator();
beforeUpdateIterator();
afterUpdateIterator();
beforeDeleteIterator();
afterDeleteIterator();

which would automatically force developer to write the filter-Condition logic inside those methods and which would populate a map based on those conditions.

This would help writing clean code and stop anyone writing from reiterating again and again.

**Comment by renatoliveira** [comment]
While I agree that this is an interesting idea, I also think this is unnecessary since you can implement this logic yourself depending on what your trigger does. In a hypothetical situation where you have a trigger that has a before insert event which implements four methods that require iterating the `Trigger.new` list, for example, you can easily create a method that handles the filtering of those records. This way, you have the framework, and you implement the filter-condition logic yourself before running your trigger logic.

1. Trigger handler is fired;
2. Iterate the records and apply the filters;
3. Call each custom method with the filtered records as you need.

Is there any particular situation where this is needed?

**Comment by pranayjswl007** [comment]
I was thinking about forcing a way so that we have to iterate over a set of record only once. I think it has more to do with process than framework itself.
