### ISSUE TITLE
Bypass does not work

### ISSUE THREAD

**Issue by splacentino** [kevinohara80/sfdc-trigger-framework#9]
Hello,

I have multiple `trigger` using this framework and the `byPass` function does not seem to work.
Version of TriggerHandler: unknown (not added on org. by myself)
E.g.:

AccountTrigger:
```apex
new AccountTriggerHandler().run();
```

AccountTriggerHandler:
```apex
AccountTriggerLogic.process(Trigger.New);
```

AccountTriggerLogic:
```apex
public static void process(Account[] accounts) { System.debug('Inside account triggerlogic'); }
```

And there is multiple statements in my code I do:
```apex
TriggerHandler.bypass('AccountTriggerHandler');
update account;
TriggerHandler.clearBypass('AccountTriggerHandler');
```

In my logs I can see that the `AccountTriggerHandler` is not bypassed.
Is there any update to do ?

**Comment by codefriar** [comment]
This can happen if there are multiple triggers on an object and *any one* of them is not using the trigger framework.

For instance: if the account object has 3 triggers, and only 2 of them are using the trigger framework, then when the third trigger fires, it does *not* bypass the others.

-Kevin

**Comment by splacentino** [comment]
@codefriar Ok thank you for the explaination.

It seems that some of managed package installed are not using the framework.
My thougth was:

AccountTrigger -> Handler -> bypassed
AccountTrigger2 -> No handler -> code executed
AccountTrigger3 -> No handler -> code executed

How can this cenario does force Accounttrigger to execute the handler?

**Comment by kevinohara80** [comment]
Well there are a bunch of different scenarios that could be at play here. It's hard to tell without knowing what's happening in your org. Keep in mind the following:

- The code to bypass the trigger needs to run in order to have the trigger bypassed. As @codefriar mentioned, other triggers that are running might be doing DML to an account before your bypass code has had a chance to run.
- The bypassing of triggers becomes really difficult to guarantee when there are other triggers in the mix...especially triggers out of your control (i.e. managed packages).
- In many cases, a full "bypass" of a trigger is not the best option. You could always look for creative ways in your trigger logic to bypass certain functionality.
- And of course, you cannot control the order of trigger execution. That also causes problems. Your trigger architecture needs to account for that.

I hope this helps.

**Comment by splacentino** [comment]
@kevinohara80 

+ You are right, I just realised this.
+ True
+ Full bypass is less time consuming on certain project but I fully agree and it is the case in my logic.
+ The order execution is not an issue for us, hopefully the job has been well done.

Thank you both for your quick and complete answers
